bancolombia/scaffold-clean-architecture

- .travis.yml
Changed the task publishPlugins
> Fix pipeline travis

- README.md
- build.gradle
- gradle.properties
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/Utils.java
- src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
- src/main/java/co/com/bancolombia/task/GenerateUseCaseTask.java
- src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
- src/main/java/co/com/bancolombia/templates/Constants.java
- src/main/java/co/com/bancolombia/templates/DrivenAdapterTemplate.java
- src/main/java/co/com/bancolombia/templates/PluginTemplate.java
- src/main/java/co/com/bancolombia/templates/ScaffoldTemplate.java
- src/main/java/co/com/bancolombia/templates/UseCaseTemplate.java
- src/test/java/co/com/bancolombia/task/GenerateUseCaseTaskTest.java
- Include the UseCase Word in class name
- Fix the package name at MainApplication class
- Fix JPA Repository has no reference for JPA Repository
> Issue 20, 21 and 22

- .github/workflows/gradle.yml
> Update Dependence helper-jpa

- src/main/java/co/com/bancolombia/templates/ScaffoldTemplate.java
#35 & #43  -> Fixed, @andmagom does not do the unit test unification with jacoco, instead it does the test unification with net.salima.cobertura plugin
> Removing jacoco pluging and adding cobertura plugin

- .github/workflows/gradle.yml
- build.gradle
- src/test/java/co/com/bancolombia/models/drivenadapters/AsyncEventBusDrivenAdapterTest.java
- src/test/java/co/com/bancolombia/models/drivenadapters/MongoDrivenAdapterTest.java
- src/test/java/co/com/bancolombia/models/entrypoints/ApiReactiveTest.java
- src/test/java/co/com/bancolombia/models/entrypoints/ApiRestTest.java
- src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java
- src/test/java/co/com/bancolombia/task/ValidateStructureTaskTest.java
- src/test/java/co/com/bancolombia/templates/config/JpaConfigTemplateTest.java
- src/test/java/co/com/bancolombia/templates/properties/PropertiesTemplateTest.java
The github pipeline is not able to get the jacoco file report.xml
> fix path on unit test and removing properties from build.gradle

- README.md
- gradle.properties
- src/main/java/co/com/bancolombia/templates/PluginTemplate.java
- src/main/java/co/com/bancolombia/templates/ScaffoldTemplate.java
- src/main/java/co/com/bancolombia/templates/deployment/AzureDevOpsPipelineTemplate.java
- Change of cobertura plugin for jacoco plugin
- Unnecessary blocks in build gradle and main gradle removed
- Fix application yaml space
- Redundant annotation @EnableAutoConfiguration removed
> Change of cobertura plugin for jacoco plugin

- README.md
- gradle.properties
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/PluginClean.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
- src/main/java/co/com/bancolombia/utils/FileAppender.java
- src/main/java/co/com/bancolombia/utils/FileUpdater.java
- src/main/java/co/com/bancolombia/utils/Utils.java
- src/main/resources/structure/root/settings.gradle.mustache
- src/test/java/co/com/bancolombia/factory/ModuleBuilderTest.java
- src/test/java/co/com/bancolombia/task/DeleteModuleTaskTest.java
- src/test/java/co/com/bancolombia/utils/UtilsTest.java
Implements:
- #63 Delete existent entry point or driven adapter
> Task that allows delete existing subproject

- README.md
- src/main/resources/structure/root/readme.md.mustache
> Add new documentation to readme file

- README.md
- gradle.properties
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/task/CleanArchitectureDefaultTask.java
- src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
- src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
- src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
- src/main/java/co/com/bancolombia/task/GenerateModelTask.java
- src/main/java/co/com/bancolombia/task/GeneratePipelineTask.java
- src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
- src/main/java/co/com/bancolombia/task/GenerateUseCaseTask.java
- src/test/java/co/com/bancolombia/task/CleanArchitectureDefaultTaskTest.java
Implements:
- #60  Improves error messages when invalid task usage.
> print help on error task usage

- README.md
Se corrigen parámetros opcionales en documentación
> Se corrige documentación

- build.gradle
- src/main/java/co/com/bancolombia/Constants.java
- src/main/resources/pipeline/azure/azure.yaml.mustache
- src/main/resources/structure/root/build.gradle.mustache
Update sonarqube properties from build.gradle to execute the cleaner analysis task in the pipeline
> Update gradle task for sonarqube integration

- README.md
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/exceptions/CleanException.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestWebflux.java
- src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
- src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
- src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
- src/main/java/co/com/bancolombia/utils/Utils.java
- src/main/resources/entry-point/rest-webflux/router-functions/definition.json
- src/main/resources/entry-point/rest-webflux/router-functions/handler.java.mustache
- src/main/resources/entry-point/rest-webflux/router-functions/router.java.mustache
- src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java
- src/test/java/co/com/bancolombia/task/GenerateStructureTaskTest.java
- src/test/java/co/com/bancolombia/task/ValidateStructureTaskTest.java
Can use router functions in webflux and RestController the default option is router functions
> Can use router functions in webflux

- README.md
- gradle.properties
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
- src/main/resources/structure/root/build.gradle.mustache
- src/main/resources/structure/root/main.gradle.mustache
- src/test/java/co/com/bancolombia/task/ValidateStructureTaskTest.java
Fix dependency managment.
Upgrade the version of spring Boot from 2.2.8 to 2.3.8
> Fix and upgrade new version springboot

- .github/workflows/gradle.yml
> java 11 updated in pipelines

- .github/workflows/gradle.yml
- README.md
- build.gradle
- gradle.properties
- src/main/java/co/com/bancolombia/Constants.java
> Fix compatibility

- README.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/co/com/bancolombia/Constants.java
- src/main/resources/structure/root/main.gradle.mustache
- Upgrade gradle  wrapper from 5.6.3 to 6.7
- Upgrade Spring boot  from 3.8-RELEASE to 4.2
> Upgrade gradle and spring version

- src/main/resources/driven-adapter/r2dbc-postgresql/config/postgresql-connection-pool.java.mustache
- src/main/resources/driven-adapter/r2dbc-postgresql/config/postgresql-connection-properties.java.mustache
- src/main/resources/driven-adapter/r2dbc-postgresql/my-reactive-repository.java.mustache
Added missing semicolons in package declarations for R2DBC mustache files. Issue #150
> Added missing semicolons

- src/main/resources/structure/root/readme.md.mustache
improve the documentation of automatic beans
> Update documentation of beans 

- README.md
- src/main/java/co/com/bancolombia/PluginClean.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/tests/AcceptanceTest.java
- src/main/java/co/com/bancolombia/factory/tests/ModuleFactoryTests.java
- src/main/java/co/com/bancolombia/task/GenerateAcceptanceTestTask.java
- src/main/java/co/com/bancolombia/utils/FileUtils.java
- src/main/resources/test/acceptance-test/TestParallel.java.mustache
- src/main/resources/test/acceptance-test/build.gradle.mustache
- src/main/resources/test/acceptance-test/definition.json
- src/main/resources/test/acceptance-test/example/demo.runner.java.mustache
- src/main/resources/test/acceptance-test/readme.md.mustache
- src/main/resources/test/acceptance-test/resources/demo.feature.mustache
- src/main/resources/test/acceptance-test/resources/karate-config.js.mustache
- src/main/resources/test/acceptance-test/resources/logback-test.xml.mustache
- src/main/resources/test/acceptance-test/settings.gradle.mustache
- src/test/java/co/com/bancolombia/factory/tests/ModuleFactoryTestsTest.java
- src/test/java/co/com/bancolombia/task/GenerateTestTaskTest.java
- Fix bug Resources should be closed in file utils
- Remove log lifecycle in validate structure task
- Acceptance Test With Karate Framework
> Acceptance Test With Karate Framework

- src/main/resources/driven-adapter/async-event-bus/build.gradle.mustache
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/build.gradle.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/build.gradle.mustache
- src/main/resources/driven-adapter/generic/build.gradle.mustache
- src/main/resources/driven-adapter/jpa-repository/build.gradle.mustache
- src/main/resources/driven-adapter/kms-reactive/build.gradle.mustache
- src/main/resources/driven-adapter/kms/build.gradle.mustache
- src/main/resources/driven-adapter/mongo-reactive/build.gradle.mustache
- src/main/resources/driven-adapter/mongo-repository/build.gradle.mustache
- src/main/resources/driven-adapter/mq-sender/build.gradle.mustache
- src/main/resources/driven-adapter/r2dbc-postgresql/build.gradle.mustache
- src/main/resources/driven-adapter/redis-reactive/redis-repository/build.gradle.mustache
- src/main/resources/driven-adapter/redis-reactive/redis-template/build.gradle.mustache
- src/main/resources/driven-adapter/redis/redis-repository/build.gradle.mustache
- src/main/resources/driven-adapter/redis/redis-template/build.gradle.mustache
- src/main/resources/driven-adapter/rsocket-requester/build.gradle.mustache
- src/main/resources/driven-adapter/s3-reactive/build.gradle.mustache
- src/main/resources/driven-adapter/s3/build.gradle.mustache
- src/main/resources/entry-point/async-event-handler/build.gradle.mustache
- src/main/resources/entry-point/generic/build.gradle.mustache
- src/main/resources/entry-point/graphql-api/build.gradle.mustache
- src/main/resources/entry-point/mq-listener/build.gradle.mustache
- src/main/resources/structure/applications/appservice/build.gradle.mustache
- src/main/resources/structure/domain/usecase/build.gradle.mustache
- src/main/resources/usecase/build.gradle.mustache
> Upgrade configurations gradle 7

- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
Add delete module task for kotlin
> Add task module delete kotlin

- README.md
Using kotlin for kotlin structure picture
Change the right title for kotlin structure picture
> Change the right title for kotlin structure picture

- .github/workflows/gradle.yml
- build.gradle
> Publish artifact in github packages

- src/main/java/co/com/bancolombia/Constants.java
- src/main/resources/driven-adapter/mq-sender-sync/sample-mq-message-sender.java.mustache
- src/main/resources/driven-adapter/mq-sender-sync/sample-mq-message-sender.kt.mustache
- src/main/resources/driven-adapter/mq-sender/sample-mq-message-sender.java.mustache
- src/main/resources/driven-adapter/mq-sender/sample-mq-message-sender.kt.mustache
> upgrade commons-jms

- build.gradle
> Update java version

- README.md
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterDynamoDB.java
- src/main/java/co/com/bancolombia/factory/adapters/ModuleFactoryDrivenAdapter.java
- src/main/resources/driven-adapter/dynamo-db/build.gradle.kts.mustache
- src/main/resources/driven-adapter/dynamo-db/build.gradle.mustache
- src/main/resources/driven-adapter/dynamo-db/config/dynamodb-config.java.mustache
- src/main/resources/driven-adapter/dynamo-db/config/dynamodb-config.kt.mustache
- src/main/resources/driven-adapter/dynamo-db/definition.json
- src/main/resources/driven-adapter/dynamo-db/dynamo-db-template-adapter.java.mustache
- src/main/resources/driven-adapter/dynamo-db/dynamo-db-template-adapter.kt.mustache
- src/main/resources/driven-adapter/dynamo-db/helper/adapter-operations.java.mustache
- src/main/resources/driven-adapter/dynamo-db/helper/adapter-operations.kt.mustache
- src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterKotlinTaskTest.java
- src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java
Add new driven adapter for Amazon Dynamo DB
> add driven adapter dynamo DB to kotlin and java

- .github/workflows/gradle.yml
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterDynamoDB.java
- src/main/resources/driven-adapter/async-event-bus/reactive-direct-async-gateway.java.mustache
- src/main/resources/driven-adapter/async-event-bus/reactive-direct-async-gateway.kt.mustache
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/rest-consumer.java.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/build.gradle.kts.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/build.gradle.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/config/dynamodb-config.java.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/config/dynamodb-config.kt.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/definition.json
- src/main/resources/driven-adapter/dynamo-db-reactive/dynamo-db-template-adapter.java.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/dynamo-db-template-adapter.kt.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/helper/adapter-operations.java.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/helper/adapter-operations.kt.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/modelEntity.java.mustache
- src/main/resources/driven-adapter/dynamo-db-reactive/modelEntity.kt.mustache
- src/main/resources/driven-adapter/dynamo-db/config/dynamodb-config.java.mustache
- src/main/resources/driven-adapter/dynamo-db/config/dynamodb-config.kt.mustache
- src/main/resources/driven-adapter/dynamo-db/definition.json
- src/main/resources/driven-adapter/dynamo-db/dynamo-db-template-adapter.java.mustache
- src/main/resources/driven-adapter/dynamo-db/helper/adapter-operations.java.mustache
- src/main/resources/driven-adapter/dynamo-db/modelEntity.java.mustache
- src/main/resources/driven-adapter/mq-sender/sample-mq-message-sender.kt.mustache
- src/main/resources/driven-adapter/s3/s3-adapter.java.mustache
- src/main/resources/driven-adapter/s3/s3-adapter.kt.mustache
> Improve DynamoDB Adapter

- src/main/java/co/com/bancolombia/Constants.java
upgrade reactive commons to 1.0.4 version
> upgrade reactive commons

- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/Constants.java
- src/main/resources/structure/applications/appservice/build.gradle.kts.mustache
- src/main/resources/structure/applications/appservice/build.gradle.mustache
Upgrade spring boot version.
Set custom output jar name from root project name.
Remove plain jar generation.
> upgrade spring boot dependency version and set specific output jar name

- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpdateDependencies.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M04D26.java
- src/main/java/co/com/bancolombia/task/GenerateModelTask.java
- src/main/java/co/com/bancolombia/task/GenerateUseCaseTask.java
fix isKotlin method, fix language property, hide loadPackage function, fix dependencies replace expression
> Fix upgrades

- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/utils/RestConsumer.java
- src/test/java/co/com/bancolombia/factory/ModuleBuilderTest.java
- src/test/java/co/com/bancolombia/task/UpdateProjectTaskTest.java
- src/test/java/co/com/bancolombia/utils/UtilsTest.java
> Fix  code smells

- src/main/resources/pipeline/github/github.yaml.mustache
Upgrade the template of github action, updating the version of the libraries [setup-java](https://github.com/actions/setup-java) to v2 using temurin jdk and [checkout](https://github.com/actions/checkout) to v3
> Update github action

- .github/workflows/secret-scanner.yml
Activate secrets scannning tool on github repository
> Activate secrets scannning tool

- src/main/java/co/com/bancolombia/Constants.java
Upgrade commons jms library version which implements reconnections to mq
> upgrade to latest commons jms library with reconnections

- src/main/resources/pipeline/azure/azure.yaml.mustache
Fix SonarQube properties for correct static analysis of source code. 
Updates the versions of the tasks in the pipeline. 
Adds pipeline schema reference as code and enhancements to the pipeline.
> fix azure devops pipeline

- src/main/java/co/com/bancolombia/Constants.java
Upgrade root dependencies (spring boot 2.7.2, jacoco, aws bom and lombok), closes #268
> Upgrade root dependencies

- src/main/resources/driven-adapter/consumer-rest/rest-consumer/build.gradle.kts.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/build.gradle.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/rest-consumer.java.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/rest-consumer.kt.mustache
Update okhttp3 client version to latest 4.x, closes #267
> Update okhttp3 to latest version 4.x

- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M08D08.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M08D08Test.java
- src/test/resources/gradle-8-sample/after.txt
- src/test/resources/gradle-8-sample/before.txt
Reports settings update for compatibility with gradle 8
> Preparing for compatibility with next gradle 8

- README.md
- gradle.properties
- src/main/java/co/com/bancolombia/CleanPluginExtension.java
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/ModelProps.java
- src/main/java/co/com/bancolombia/PluginClean.java
- src/main/java/co/com/bancolombia/models/TaskModel.java
- src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
- src/test/java/co/com/bancolombia/task/ValidateStructureTaskTest.java
- Added extension property to white list dependencies on model validation.
- Improved logs pointing to validation errors
> feat(model_validation): added extension property to white list dependencies

- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M01D12.java
- src/main/resources/structure/root/settings.gradle.mustache
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M01D12Test.java
- src/test/resources/settings-gradle-sample/after.txt
- src/test/resources/settings-gradle-sample/before.txt
Add pluginManagement to settings.gradle closes #293
> add pluginManagement closes #293

- .github/workflows/gradle.yml
- README.md
- build.gradle
- src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
- src/main/java/co/com/bancolombia/PluginClean.java
- src/main/java/co/com/bancolombia/analytics/AnalyticsBody.java
- src/main/java/co/com/bancolombia/analytics/AnalyticsExporter.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/task/AnalyticsTask.java
- src/main/java/co/com/bancolombia/task/CleanArchitectureDefaultTask.java
- src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
- src/main/java/co/com/bancolombia/task/GenerateAcceptanceTestTask.java
- src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
- src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
- src/main/java/co/com/bancolombia/task/GenerateHelperTask.java
- src/main/java/co/com/bancolombia/task/GenerateModelTask.java
- src/main/java/co/com/bancolombia/task/GeneratePipelineTask.java
- src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
- src/main/java/co/com/bancolombia/task/GenerateUseCaseTask.java
- src/main/java/co/com/bancolombia/task/UpdateProjectTask.java
- src/main/java/co/com/bancolombia/utils/FileUtils.java
- src/main/java/co/com/bancolombia/utils/RestConsumer.java
- src/test/java/co/com/bancolombia/factory/ModuleBuilderTest.java
- src/test/java/co/com/bancolombia/task/AnalyticsTaskTest.java
Generate task usage analytics closes #289
> Generate usage analytics to improve project efforts, closes #289

- .github/workflows/gradle.yml
Update gradle actions to generate changelog when a release is published, closes #259
> Add changelog generation

- .github/workflows/gradle.yml
- .gitignore
- README.md
- gradle.properties
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointGraphql.java
- src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
- src/main/resources/entry-point/graphql-api/build.gradle.kts.mustache
- src/main/resources/entry-point/graphql-api/build.gradle.mustache
- src/main/resources/entry-point/rest-webflux/router-functions/router.java.mustache
- src/main/resources/structure/root/build.gradle.mustache
Update GraphQL resources closes #316 
base project + defaults java version and reactive projects
> base project + graphql + defaults java version and reactive projects

- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/config/rest-consumer-config.java.mustache
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/config/rest-consumer-config.kt.mustache
- src/main/resources/driven-adapter/kms-reactive/kms-adapter.java.mustache
- src/main/resources/driven-adapter/kms-reactive/kms-adapter.kt.mustache
Features:
- remove unnecessary kms keyId param
- remove self signed certificate for http
> remove unnecessary kms keyId param

- src/main/resources/driven-adapter/mongo-reactive/config/mongo-config.java.mustache
- src/main/resources/driven-adapter/mongo-repository/config/mongo-config.java.mustache
- remove unnecessary environment object
Closes #321
> remove unnecessary environment object

- src/main/java/co/com/bancolombia/Constants.java
update secrets library version, closes #326
> update secrets library version, closes #326

- src/main/java/co/com/bancolombia/Constants.java
Update dependency version closes #318
> update reactive commons library version, closes #318

- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/upgrades/UpdateUtils.java
- src/main/java/co/com/bancolombia/factory/upgrades/UpgradeMainGradle.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M05D03.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M05D05.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M01D12.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M02D08JavaxJakarta.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M02D08Redis.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M02D13Gradle.java
- src/main/java/co/com/bancolombia/task/UpdateProjectTask.java
- src/main/java/co/com/bancolombia/utils/CommandUtils.java
- src/main/resources/structure/applications/appservice/build.gradle.mustache
- src/main/resources/structure/root/main.gradle.mustache
- src/test/java/co/com/bancolombia/factory/upgrades/UpdateUtilsTest.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpdatePluginVersionTest.java
- src/test/java/co/com/bancolombia/factory/upgrades/samples/AnUpdate.java
…ile method
add new updates from sb2 to sb3, export applied directly from updateFile method
> Add new updates from sb2 to sb3

- gradle.properties
- src/main/java/co/com/bancolombia/adapters/RestService.java
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/upgrades/UpdateUtils.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpdateDependencies.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M04D27.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M05D02.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M08D08.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M02D08Java.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M02D14RestMapping.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/ZUpdateGenericDependenciesVersion.java
- src/main/java/co/com/bancolombia/models/DependencyRelease.java
- src/main/java/co/com/bancolombia/models/DependencyReleasesDeserializer.java
- src/main/java/co/com/bancolombia/utils/Utils.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpdateDependenciesTest.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M04D27Test.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M02D14RestMappingTest.java
- src/test/java/co/com/bancolombia/utils/UtilsTest.java
- src/test/resources/rest/mapping-after.txt
- src/test/resources/rest/mapping-before.txt
add replace group of a regex, remove / from the end of request mappings path.
Related to #317 #312
> Update rest entrypoint RequestMapping path

- .github/workflows/gradle.yml
> fix release task

- .github/workflows/gradle.yml
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M08D10.java
- src/test/resources/junit-platform/with.txt
Fix gradle u failure by index error in string
> fix upgrade junit

- src/main/resources/entry-point/graphql-api/api-mutations.java.mustache
- src/main/resources/entry-point/graphql-api/api-queries.java.mustache
- src/main/resources/entry-point/rest-mvc/api.java.mustache
- src/main/resources/entry-point/rest-mvc/api.unit.test.java.mustache
- src/main/resources/entry-point/rest-mvc/definition.json
- src/main/resources/entry-point/rest-webflux/api.java.mustache
- src/main/resources/entry-point/rsocket-responder/rsocket-responder.java.mustache
- src/main/resources/model/model.java.mustache
- src/main/resources/test/performance-test/jmeter/Jmeter/Api/SC_Template_HTTP_Service.jmx.mustache
- src/main/resources/test/performance-test/jmeter/Jmeter/Api/SC_Template_UDP_Service.jmx.mustache
- src/main/resources/test/performance-test/jmeter/definition.json
- src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java
Performance test update and test fix
> Performance test update and test fix

- .github/workflows/gradle.yml
- build.gradle
> fix(actions) to GitHub repo

- .github/workflows/release.yml
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/factory/upgrades/UpdateUtils.java
- src/main/java/co/com/bancolombia/factory/upgrades/UpgradeMainGradle.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M01D12.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M05D04BlockHound.java
- src/main/java/co/com/bancolombia/task/AbstractCleanArchitectureDefaultTask.java
- src/test/java/co/com/bancolombia/factory/upgrades/UpdateUtilsTest.java
refactor utils name for clarity, remove lifecycle logs, enable it as info
> fix(refactor): refactor utils name for clarity, remove lifecycle logs

- .github/workflows/gradle.yml
- src/main/java/co/com/bancolombia/PluginClean.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M06D01SpringPlugin.java
- src/main/resources/structure/root/build.gradle.mustache
- src/test/java/co/com/bancolombia/PluginCleanTest.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M06D01SpringPluginTest.java
- src/test/resources/springplugin/after.txt
- src/test/resources/springplugin/before.txt
Fix spring plugin in root project
> Fix spring plugin in root project

- .github/workflows/release.yml
> fix(library release): library release as job

- .github/workflows/release.yml
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRestConsumer.java
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/build.gradle.mustache
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/config/rest-consumer-config.java.mustache
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/rest-consumer.java.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/build.gradle.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/rest-consumer.java.mustache
Implement circuit breaker in rest consumers
> feat(circuit breaker): Applied to rest consumer

- src/main/resources/test/performance-test/jmeter/Jmeter/ColasMQ/README.md.mustache
- src/main/resources/test/performance-test/jmeter/Jmeter/ColasMQ/SC_Template_ColasMQ.jmx.mustache
- src/main/resources/test/performance-test/jmeter/definition.json
> feat(performanceTest): Cambio de rama

- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterBinStash.java
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterDynamoDB.java
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterKtor.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M10D02SonarRules.java
- src/main/java/co/com/bancolombia/factory/validations/architecture/ArchitectureValidation.java
- src/main/resources/structure/applications/appservice/arch-validations/.gitignore.mustache
- src/main/resources/structure/applications/appservice/arch-validations/architecture-test.java.mustache
- src/main/resources/structure/applications/appservice/arch-validations/definition.json
- src/main/resources/structure/applications/appservice/arch-validations/utils.java.mustache
- src/main/resources/structure/applications/appservice/build.gradle.mustache
- src/main/resources/structure/root/build.gradle.mustache
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M10D02SonarRulesTest.java
- src/test/resources/sonar-rules/after.txt
- src/test/resources/sonar-rules/before.txt
Translate ArchUnit violations to sonar issues
> Translate ArchUnit violations to sonar issues

- src/main/java/co/com/bancolombia/factory/commons/GenericModule.java
Fixes #351 fix dash generic modules
> fix dash generic modules

- src/main/java/co/com/bancolombia/exceptions/CleanUncheckedException.java
- src/main/java/co/com/bancolombia/exceptions/InvalidStateException.java
- src/main/java/co/com/bancolombia/factory/upgrades/UpdateUtils.java
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M05D04BlockHound.java
- src/test/java/co/com/bancolombia/factory/upgrades/UpdateUtilsTest.java
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M05D04BlockHoundTest.java
- src/test/resources/blockhound/after.txt
- src/test/resources/blockhound/before-err.txt
Fix blockhound update issue #366
> Fix upgrade blockhound

- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M10D02JacocoMerged.java
- src/main/resources/structure/root/main.gradle.mustache
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M10D02JacocoMergedTest.java
- src/test/resources/jacoco-merged/after.txt
- src/test/resources/jacoco-merged/before.txt
Fixes undeclared jacocoMergedReport dependency on test task
> fix(jacoco): Dependency on test task, Closes #384

- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterS3.java
- src/main/resources/driven-adapter/consumer-rest/object-request.java.mustache
- src/main/resources/driven-adapter/consumer-rest/object-response.java.mustache
- src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/config/rest-consumer-config.java.mustache
- src/main/resources/driven-adapter/jpa-repository/helper/adapter-operations.java.mustache
- src/main/resources/driven-adapter/kms-reactive/kms-adapter.java.mustache
- src/main/resources/driven-adapter/kms/kms-adapter.java.mustache
- src/main/resources/driven-adapter/mongo-repository/helper/adapter-operations.java.mustache
- src/main/resources/driven-adapter/r2dbc-postgresql/helper/reactive-adapter-operations.java.mustache
- src/main/resources/driven-adapter/sqs-reactive/sqs-sender.java.mustache
- src/main/resources/driven-adapter/sqs/sqs-sender.java.mustache
- src/main/resources/entry-point/sqs-reactive/sqs-listener.java.mustache
- src/main/resources/entry-point/sqs-reactive/sqs-processor.java.mustache
- Fix Architecture test fails in the restconsumer and KMS issue #395 
- Add SuppressWarnings annotation in adapter operations
- Update localstack endpoint for S3 in local environment
> fix: Add @value annotation in the constructor

- README.md
- src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointKafka.java
- src/main/resources/entry-point/kafka-consumer-reactive/build.gradle.mustache
- src/main/resources/entry-point/kafka-consumer-reactive/definition.json
- src/main/resources/entry-point/kafka-consumer-reactive/kafka-config.java.mustache
- src/main/resources/entry-point/kafka-consumer-reactive/kafka-consumer.java.mustache
- src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java
Add basic reactive kafka consumer
> Add basic reactive kafka consumer

- .github/workflows/gradle.yml
- src/main/java/co/com/bancolombia/Constants.java
> Update ArchUnit version

- src/main/java/co/com/bancolombia/Constants.java
> feat(kafka): Add reactive kafka consumer, update archunit and resilience

- .github/workflows/release.yml
> fix(actions): enable push for automatic release

- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M12D15Gradle.java
- src/main/resources/structure/root/build.gradle.mustache
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M12D15GradleTest.java
- src/test/resources/build-gradle/sonarqube-task-after.txt
- src/test/resources/build-gradle/sonarqube-task-before.txt
Fix sourceEncoding property for sonarqube task and set jacocoMergedReport path to xmlReportPaths property on build.gradle root file
> Fix Sonar properties

- src/main/java/co/com/bancolombia/Constants.java
fix(deps): Update base dependencies
> fix(deps): Update base dependencies

- README.md
- src/main/java/co/com/bancolombia/task/GeneratePipelineTask.java
- src/main/resources/pipeline/azure/azure.yaml.mustache
- src/test/java/co/com/bancolombia/task/GeneratePipelineTaskTest.java
Add new optional parameter to improve pipelines implementations
> feat: add optional parameter in pipeline task

- README.md
- build.gradle
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/test/java/co/com/bancolombia/task/GenerateStructureTaskTest.java
fix(gradle): Fix jackson compilation error and specify gradle version in readme
> fix(gradle): Fix jackson compilation error and specify gradle version in readme

- README.md
Update readme with supported java versions
> docs(readme): Update java version options in readme

- .github/workflows/gradle.yml
- build.gradle
- src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M01D10Sonar.java
- src/main/resources/structure/root/build.gradle.mustache
- src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M01D10SonarTest.java
- src/test/resources/sonarqube-2-sonar/sonarqube-task-after.txt
- src/test/resources/sonarqube-2-sonar/sonarqube-task-before.txt
fix(sonar): Update deprecated sonarqube task to sonar
> fix(sonar): Update deprecated sonarqube task to sonar

- .github/pull_request_template.md
- README.md
- generate_project.sh
- publish_plugin_local.sh
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterBinStash.java
- src/main/java/co/com/bancolombia/task/AbstractCleanArchitectureDefaultTask.java
- src/main/resources/driven-adapter/async-event-bus/events-gateway.java.mustache
- src/main/resources/driven-adapter/async-event-bus/reactive-direct-async-gateway.java.mustache
- src/main/resources/driven-adapter/async-event-bus/reactive-events-gateway.java.mustache
- src/main/resources/driven-adapter/bin-stash/bin-stash-local-cache-config.java.mustache
- src/main/resources/driven-adapter/bin-stash/build.gradle.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/rest-consumer.java.mustache
- src/main/resources/driven-adapter/consumer-rest/rest-consumer/rest-consumer.test.java.mustache
- src/main/resources/driven-adapter/jpa-repository/build.gradle.mustache
- src/main/resources/driven-adapter/mongo-reactive/config/mongo-config.java.mustache
- src/main/resources/driven-adapter/mongo-reactive/config/mongo-config.unit.test.java.mustache
- src/main/resources/driven-adapter/mongo-repository/config/mongo-config.java.mustache
- src/main/resources/driven-adapter/s3-reactive/s3-operations.java.mustache
- src/main/resources/entry-point/sqs-reactive/sqs-configTest.java.mustache
- src/main/resources/entry-point/sqs-reactive/sqs-listenerTest.java.mustache
- src/main/resources/entry-point/sqs/sqs-configTest.java.mustache
- src/main/resources/entry-point/sqs/sqs-listenerTest.java.mustache
- src/main/resources/structure/applications/appservice/build.gradle.mustache
- Solves some issues compiling and scanning generated code (mongo, sqs, consumer rest, metrics, binstash, dependencyCheck).
- Reorganize readme, sort adapters by name.
- Update pull request template.
> fix(scan): Solves some issues compiling and scanning generated code

- .github/workflows/gradle.yml
Enforce conventional commits on PR
> ci(commits): Verify commit message with semantic release standard

- src/main/java/co/com/bancolombia/Constants.java
> fix(spring): update spring boot and aws bom

- .github/workflows/gradle.yml
- src/main/java/co/com/bancolombia/Constants.java
> fix(deps): Update deps

- build.gradle
- src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
- src/main/java/co/com/bancolombia/models/DependencyRelease.java
- src/main/java/co/com/bancolombia/models/DependencyReleaseXml.java
- src/main/java/co/com/bancolombia/utils/Utils.java
- src/main/java/co/com/bancolombia/utils/offline/LocalTasks.java
- src/main/java/co/com/bancolombia/utils/offline/UpdateProjectDependencies.java
- src/test/java/co/com/bancolombia/utils/offline/UpdateProjectDependenciesTest.java
Add update tool for local upgrade of build.gradle
> ci(autoupdate): Update build.gradle

- .github/workflows/updater.yml
Add automatic pull request with updates that runs every monday at 7:00
> ci(deps): Autoupdate dependencies

- gradle.properties
- src/main/java/co/com/bancolombia/task/InternalTask.java
- src/main/java/co/com/bancolombia/task/UpdateProjectTask.java
- src/main/java/co/com/bancolombia/utils/Utils.java
- src/main/java/co/com/bancolombia/utils/offline/UpdateProjectDependencies.java
- src/test/java/co/com/bancolombia/task/InternalTaskTest.java
- src/test/java/co/com/bancolombia/utils/UtilsTest.java
- src/test/java/co/com/bancolombia/utils/offline/UpdateProjectDependenciesTest.java
feat(updater): Export updater logic as task for another non clean architecture projects
> feat(updater): Export updater logic as task for another non clean architecture projects

- src/main/java/co/com/bancolombia/factory/validations/architecture/ArchitectureValidation.java
Fix concurrency issue with archunit tests
> fix(concurrent): fix map concurrency error

- src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvc.java
- src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointWebflux.java
- src/main/java/co/com/bancolombia/factory/validations/architecture/ArchitectureValidation.java
- src/main/java/co/com/bancolombia/utils/Utils.java
- Alternative method for seaching for a project's dependency, fixing ConcurrentModificationExceptions.
- Fix Archunit test for rest-mvc entrypoints
> fix: dependency tree traversing

- .github/workflows/gradle.yml
- .github/workflows/updater.yml
Add build conditions for checkout
> build(conditions): Use github app only with main branch

- docs/docs/2-getting-started.md
- docs/docusaurus.config.js
> docs(docusaurus): fix broken links

- src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointSQS.java
- src/main/resources/entry-point/sqs-reactive/sqs-listener.java.mustache
- src/main/resources/entry-point/sqs-reactive/sqs-properties.java.mustache
- src/main/resources/entry-point/sqs/sqs-listener.java.mustache
- src/main/resources/entry-point/sqs/sqs-properties.java.mustache
fix(sqs): Fix visibility timeout value, because set to 10000 seconds
> fix(sqs): Fix visibility timeout value, because set to 10000 seconds

- docs/docs/2-getting-started.md
> docs: Update 2-getting-started.md

- .github/workflows/docs.yml
- docs/package.json
- docs/version.js
> docs: Update docs version to keep it updated

- docs/docs/2-getting-started.md
- docs/docs/tasks/_category_.json
- docs/package-lock.json
- docs/package.json
- docs/version.js
> docs(version): Update dependencies and docs

- .github/workflows/gradle.yml
> ci(sonar): Update gradle.yml

- docs/docs/tasks/5-generate-driven-adapter.md
- docs/docs/tasks/6-generate-entry-point.md
- src/main/java/co/com/bancolombia/Constants.java
- src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
- src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
- src/main/resources/driven-adapter/async-event-bus/build.gradle.mustache
- src/main/resources/driven-adapter/async-event-bus/reactive-direct-async-gateway.java.mustache
- src/main/resources/driven-adapter/async-event-bus/reactive-events-gateway.java.mustache
- src/main/resources/entry-point/async-event-handler/build.gradle.mustache
- src/main/resources/entry-point/async-event-handler/commands-handler.java.mustache
- src/main/resources/entry-point/async-event-handler/commands-handler.test.java.mustache
- src/main/resources/entry-point/async-event-handler/events-handler.java.mustache
- src/main/resources/entry-point/async-event-handler/events-handler.test.java.mustache
- src/main/resources/entry-point/async-event-handler/handler-registry-configuration.java.mustache
- src/main/resources/entry-point/async-event-handler/handler-registry-configuration.test.java.mustache
- src/main/resources/entry-point/async-event-handler/queries-handler.java.mustache
- src/main/resources/entry-point/async-event-handler/queries-handler.test.java.mustache
- src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskReactiveTest.java
- src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskReactiveTest.java
Update reactive commons for ASYNCEVENTHANDLER entry and ASYNCEVENTBUS adapter
> fix(build): Update reactive commons templates

- .github/workflows/gradle.yml
- .github/workflows/release.yml
> fix(release): Setup java 17 in release action

- .github/workflows/gradle.yml
> ci(pr): check pull request branch

- .github/workflows/release.yml
> fix(build): update release actions

- .github/workflows/release.yml
Fix release actions permissions
> build(release): update release actions permissions
