bancolombia/scaffold-clean-architecture

src/main/resources/structure/root/lombok.config.mustache

I've added a new property in the lombok.config to fix troubles with the code coverage when you are using lombok annotations

Improve code coverage in sonar with lombok

---

README.md
gradle.properties
src/main/java/co/com/bancolombia/Constants.java
src/main/resources/driven-adapter/jpa-repository/build.gradle.mustache
src/main/resources/structure/root/build.gradle.mustache
src/main/resources/structure/root/gradle.properties.mustache
src/test/java/co/com/bancolombia/task/GenerateModelTaskTest.java

- Fix #95 non available dependencies in main app service module for jpa driven adapter configuration.
- Enable #80 gradle parallel dependencies download property as default.

Fix JPA Driven Adapter Dependencies

---

README.md
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvc.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvcServer.java
src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
src/main/java/co/com/bancolombia/utils/Utils.java
src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java
src/test/java/co/com/bancolombia/utils/UtilsTest.java

* Added a new optional parameter to create a rest mvc entry point called "--server", in which you can set one of the available server (Undertow, Tomcat or Jetty)
* Added a new utility to add configurations

Implementation for issue #94

---

src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
src/main/java/co/com/bancolombia/task/GeneratePipelineTask.java
src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
src/test/java/co/com/bancolombia/task/ValidateStructureTaskTest.java

- Refactor cast with ArrayList.
- Fix validations from reactive projects.

Fix validate structure, and refactor arrayLists

---

README.md
gradle.properties
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRsocketRequester.java
src/main/java/co/com/bancolombia/factory/adapters/ModuleFactoryDrivenAdapter.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRsocketResponder.java
src/main/java/co/com/bancolombia/factory/entrypoints/ModuleFactoryEntryPoint.java
src/main/resources/driven-adapter/rsocket-requester/build.gradle.mustache
src/main/resources/driven-adapter/rsocket-requester/config/requester-config.java.mustache
src/main/resources/driven-adapter/rsocket-requester/definition.json
src/main/resources/driven-adapter/rsocket-requester/rsocket-requester.java.mustache
src/main/resources/entry-point/rsocket-responder/build.gradle.mustache
src/main/resources/entry-point/rsocket-responder/definition.json
src/main/resources/entry-point/rsocket-responder/rsocket-responder.java.mustache
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java
src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java

New feature: Users can create driven adapter and entry point of the Rsocket type, in order to establish communication through the Rsocket protocol.

Feature/rsocket components Driven adapter and Entry point

---

src/main/resources/structure/root/build.gradle.mustache
src/main/resources/structure/root/main.gradle.mustache

org.springframework.boot plugin removed from main gradle.

org.springframework.boot plugin removed

---

src/main/resources/driven-adapter/mongo-reactive/config/mongo-config.java.mustache
src/main/resources/driven-adapter/mongo-repository/config/mongo-config.java.mustache

Update mongo client factory, remove deprecated instantiation of MongoClientFactory.
Use the correct ReactiveMongoClientFactory for reactive projects.

Fix mongo client factory for reactive projects

---

README.md
gradle.properties
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointAsyncEventHandler.java
src/main/java/co/com/bancolombia/factory/entrypoints/ModuleFactoryEntryPoint.java
src/main/resources/driven-adapter/async-event-bus/definition.json
src/main/resources/driven-adapter/async-event-bus/events-gateway.java.mustache
src/main/resources/driven-adapter/async-event-bus/reactive-direct-async-gateway.java.mustache
src/main/resources/driven-adapter/async-event-bus/reactive-events-gateway.java.mustache
src/main/resources/entry-point/async-event-handler/build.gradle.mustache
src/main/resources/entry-point/async-event-handler/commands-handler.java.mustache
src/main/resources/entry-point/async-event-handler/definition.json
src/main/resources/entry-point/async-event-handler/events-handler.java.mustache
src/main/resources/entry-point/async-event-handler/handler-registry-configuration.java.mustache
src/main/resources/entry-point/async-event-handler/queries-handler.java.mustache
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java
src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java

Implements new Entry Point `ASYNCEVENTHANDLER` for events, commands and async queries using Reactive Commons abstraction. Resolves #100
Driven Adapter `ASYNCEVENTBUS` updated to be able to send commands and async queries.

Feature: new entry point for events, commands and async queries handler.

---

src/main/resources/entry-point/rest-webflux/router-functions/router.java.mustache

Fixed bug in the package "co.com.bancolombia" by variable "{{package}}" on creating the entry-point webflux.
- [] Automated tests are written
- [] The documentation is up-to-date
- [] the version of the readme.md, Constants.java and gradle.properties was increased
- [] The pull request has a descriptive title that describes what has changed, and provides enough context for the changelog

Fixed bug in the package "co.com.bancolombia" by variable "{{package}}" on creating the entry-point webflux.

---

src/main/resources/structure/root/build.gradle.mustache

Setup modules and *.gradle files automatically from gradle subprojects.

Sonarqube automatic module and sources settings

---

README.md
gradle.properties
src/main/java/co/com/bancolombia/Constants.java
src/main/resources/driven-adapter/s3-reactive/s3-operations.java.mustache
src/main/resources/driven-adapter/s3/s3-operations.java.mustache

Change name of S3Operations, according to name Class

Change Name Constructor S3Operations Without Lombok

---

build.gradle

In Gradle 7, both the compile and runtime configurations are removed. Therefore, we have to migrate to the implementation and api configurations above.

Upgrade common configuration

---

gradlew
gradlew.bat
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRestConsumer.java
src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/config/rest-consumer-config.java.mustache

improve web client reactor

---

src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterMQ.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointMQ.java
src/main/resources/driven-adapter/mq-sender-sync/build.gradle.mustache
src/main/resources/driven-adapter/mq-sender-sync/definition.json
src/main/resources/driven-adapter/mq-sender-sync/sample-mq-message-sender.java.mustache
src/main/resources/entry-point/mq-listener-sync/build.gradle.mustache
src/main/resources/entry-point/mq-listener-sync/definition.json
src/main/resources/entry-point/mq-listener-sync/sample-mq-message-listener.java.mustache

Upgrade MQ entry point and driven adapter to allow usage from non reactive projects, this update allows also the selective message listening by correlation Id.

Update commons jms

---

src/main/resources/entry-point/rest-webflux/router-functions/definition.json
src/main/resources/entry-point/rest-webflux/router-functions/router.java.mustache
src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java

When use driven adapter async event bus
and entrypoint webflux. the router entrypoint class generate conflict 

Rename router class - Webflux entrypoint

---

src/main/java/co/com/bancolombia/Constants.java
src/main/resources/driven-adapter/async-event-bus/build.gradle.mustache
src/main/resources/entry-point/async-event-handler/build.gradle.mustache
src/test/java/co/com/bancolombia/task/CleanArchitectureDefaultTaskTest.java

Upgrade of reactive commons dependency for asynceventhandler entry point and asynceventbus driven adapter.

upgrade reactive commons dependency version

---

README.md
build.gradle
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterKtorClient.java
src/main/java/co/com/bancolombia/factory/adapters/ModuleFactoryDrivenAdapter.java
src/main/java/co/com/bancolombia/factory/validations/LanguageValidation.java
src/main/resources/driven-adapter/ktor-client/build.gradle.kts.mustache
src/main/resources/driven-adapter/ktor-client/definition.json
src/main/resources/driven-adapter/ktor-client/ktor-client.kt.mustache
src/main/resources/driven-adapter/ktor-client/ktor-config.kt.mustache
src/main/resources/structure/root/build.gradle.kts.mustache
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterKotlinTaskTest.java
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java

- add new driven adapter KTOR http client for kotlin
- update spring boot version to 2.6.2
- update lombok version to 1.18.22
- update plugin dependencies

Driven adapter client ktor

---

src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvc.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestWebflux.java
src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
src/main/resources/entry-point/rest-mvc/build.gradle.kts.mustache
src/main/resources/entry-point/rest-mvc/build.gradle.mustache
src/main/resources/entry-point/rest-webflux/build.gradle.kts.mustache
src/main/resources/entry-point/rest-webflux/build.gradle.mustache
src/main/resources/entry-point/swagger/definition.json
src/main/resources/entry-point/swagger/spring-fox-config.java.mustache
src/main/resources/entry-point/swagger/spring-fox-config.kt.mustache
src/test/java/co/com/bancolombia/task/GenerateEntryPointKotlinTaskTest.java

add option for swagger in the entry point restmvc and webflux, to configure swagger documentation on "rest-controllers", the documentation will tobe in url http://host:port/swagger-ui.html

add swagger to rest entry-points include reactive

---

gradle.properties
src/main/java/co/com/bancolombia/Constants.java
src/main/resources/driven-adapter/mq-sender/definition.json
src/main/resources/driven-adapter/mq-sender/req-reply-gateway.java.mustache
src/main/resources/driven-adapter/mq-sender/sample-mq-req-reply.java.mustache

This update upgrades the mq driven adapter for `java`, and it defines the new request reply abstraction.

Feature upgrade commons jms

---

.github/workflows/gradle.yml
src/main/resources/driven-adapter/redis-reactive/redis-template/helper/reactive-template-adapter-operations.java.mustache

Add missing import for Duration class closes #162

Fix Duration class import in redis adapter close #162

---

src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvcServer.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M05D02.java
src/test/java/co/com/bancolombia/task/GenerateEntryPointKotlinTaskTest.java
src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java
src/test/java/co/com/bancolombia/utils/UtilsTest.java

Move tomcat exclusion to entry point build gradle file closes #182 
Add upgrade step to migrate from gradle 6 to 7

fix server exclusions for restmvc entrypoint close #182

---

README.md
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointSQS.java
src/main/java/co/com/bancolombia/factory/entrypoints/ModuleFactoryEntryPoint.java
src/main/java/co/com/bancolombia/utils/FileUtils.java
src/main/resources/entry-point/sqs/build.gradle.mustache
src/main/resources/entry-point/sqs/definition.json
src/main/resources/entry-point/sqs/sqs-config.java.mustache
src/main/resources/entry-point/sqs/sqs-listener.java.mustache
src/main/resources/entry-point/sqs/sqs-processor.java.mustache
src/main/resources/entry-point/sqs/sqs-properties.java.mustache
src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java

Implements new SQS Entry Point

SQS entry point

---

SECURITY.md
examples-ca/channel-operations/deployment/Dockerfile
examples-ca/example-article/deployment/Dockerfile
examples-ca/example-dynamo/deployment/Dockerfile
examples-ca/example-mongo/deployment/Dockerfile
examples-ca/example-r2dbc/deployment/Dockerfile
examples-ca/example-redis/deployment/Dockerfile
examples-ca/example-rest-consumer/rest-consumer-client/deployment/Dockerfile
examples-ca/example-rest-consumer/rest-consumer-server/deployment/Dockerfile
examples-ca/s3-example/deployment/Dockerfile
gradlew

Update Dockerfiles to use hash digest and fix this security alert:
* [Pinned-Dependencies](https://github.com/bancolombia/scaffold-clean-architecture/security/code-scanning/35)

Fix security alerts

---

build.gradle
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java

fix the functional tests and modify the gradle test execution task in the group indicated for this type of tasks and the respective description, this improves the order of the tasks.

fix functional tests

---

src/main/java/co/com/bancolombia/utils/FileUtils.java
src/main/java/co/com/bancolombia/utils/Utils.java

Fix issue #245 
Some IDEs like VSCode or Eclipse use the bin folder to compile and use resources. The plugin searches all the files by specific extension and concatenates it to the root of the test project, which generates an inconsistency in the file path, so the valid directories for file search are filtered.
Absolute paths in windows contain a disk letter is solved by validating the type of path.

fix unit tests

---

src/main/java/co/com/bancolombia/factory/ModuleBuilder.java

Use primitive boolean instead of Boolean class

---

src/main/java/co/com/bancolombia/factory/ModuleBuilder.java

Fix language name, closes #290

---

src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/task/GeneratePerformanceTestTask.java

Functional test and analytics in Performance test task

---

UPDATE.md
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRedis.java
src/main/resources/driven-adapter/r2dbc-postgresql/config/postgresql-connection-pool.unit.test.java.mustache
src/main/resources/driven-adapter/r2dbc-postgresql/definition.json
src/main/resources/driven-adapter/r2dbc-postgresql/my-reactive-repository-adapter.unit.test.java.mustache
src/main/resources/driven-adapter/redis-reactive/redis-template/build.gradle.mustache
src/main/resources/driven-adapter/redis/redis-repository/build.gradle.mustache
src/main/resources/driven-adapter/redis/redis-repository/definition.json
src/main/resources/driven-adapter/redis/redis-repository/helper/repository-adapter-operations.java.mustache
src/main/resources/driven-adapter/redis/redis-repository/model-dto.java.mustache
src/main/resources/driven-adapter/redis/redis-repository/redis-repository-adapter.java.mustache
src/main/resources/driven-adapter/redis/redis-repository/redis-repository.java.mustache
src/main/resources/driven-adapter/redis/redis-template/build.gradle.mustache
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterKotlinTaskTest.java
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java

Features:
- Removed redis reactive reactive because it is not supported by spring boot.
- Removed secrets dependency when not needed.
- Replace javax by jakarta (add explicit dependency).

Redis repository update

---

UPDATE.md
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterR2dbcPostgreSQL.java
src/main/resources/driven-adapter/jpa-repository/build.gradle.mustache
src/main/resources/driven-adapter/r2dbc-postgresql/build.gradle.mustache

Can use spring data annotations or jakarta annotations.
Improve generation with object mapper

add required dependency

---

src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M05D04BlockHound.java
src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M05D04BlockHoundTest.java
src/test/resources/blockhound/after.txt
src/test/resources/blockhound/before.txt

Add [BlockHound](https://github.com/reactor/BlockHound) validations

add block hound validations to reactive projects

---

src/main/java/co/com/bancolombia/task/AbstractResolvableTypeTask.java

Fix type parameter for after modules

fix(type): missing type parameter

---

src/main/resources/test/performance-test/jmeter/Jmeter/ColasMQ/README.md.mustache
src/main/resources/test/performance-test/jmeter/Jmeter/ColasMQ/SC_Template_ColasMQ.jmx.mustache
src/main/resources/test/performance-test/jmeter/Jmeter/ColasRabbitMQ/README.md.mustache
src/main/resources/test/performance-test/jmeter/Jmeter/ColasRabbitMQ/SC_Template_RabbitMQ.jmx.mustache
src/main/resources/test/performance-test/jmeter/definition.json

- [x ] The pull request is complete according to the [guide of contributing](https://github.com/bancolombia/scaffold-clean-architecture/wiki/Contributing)
- [x ] Automated tests are written
- [x ] The documentation is up-to-date
- [x ] The pull request has a descriptive title that describes what has changed, and provides enough context for the changelog

feat(performanceTest): Template colasMQ performa

---

src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/resources/entry-point/rest-mvc/build.gradle.mustache
src/main/resources/entry-point/rest-webflux/build.gradle.mustache

Currently, the dependency used to automate the generation of API documentation [io.springfox:springfox-boot-starter](https://github.com/springfox/springfox) has not received updates since July 13, 2020, so it is recommended to replace it with [springdoc-openapi-starter](https://github.com/springdoc/springdoc-openapi), which is maintained and updated.

Use springdoc-openapi-starter to generate API documentation

---

README.md
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvc.java
src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
src/main/resources/entry-point/rest-mvc/api.java.mustache
src/main/resources/entry-point/rest-mvc/authorization/authorization-jwt.java.mustache
src/main/resources/entry-point/rest-mvc/authorization/definition.json
src/main/resources/entry-point/rest-mvc/build.gradle.mustache

Add authorization with jwt tokens for #350 issue.
This could work with multiple identity management providers. Local tests were made with Azure AD and Keycloak.
Please don't close the issue, I would like to implement this feature to webflux.

Add authorization with jwt token in entrypoint restmvc

---

.github/workflows/gradle.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpdateDependencies.java
src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
src/main/resources/structure/deployment/dockerfile.mustache
src/test/java/co/com/bancolombia/task/GenerateStructureTaskTest.java
src/test/java/co/com/bancolombia/utils/CAAssert.java

- Add java 21 support closes #397 
- Generate gradle wrapper after structure generation

feat(gradlew): Allow update version to java 21, generate gradle wrapper

---

src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterDynamoDB.java
src/main/resources/driven-adapter/dynamo-db-reactive/config/dynamodb-config.kt.mustache
src/main/resources/driven-adapter/dynamo-db-reactive/definition.json
src/main/resources/driven-adapter/dynamo-db-reactive/dynamo-db-template-adapter.kt.mustache
src/main/resources/driven-adapter/dynamo-db-reactive/helper/adapter-operations.java.mustache
src/main/resources/driven-adapter/dynamo-db-reactive/helper/adapter-operations.kt.mustache
src/main/resources/driven-adapter/dynamo-db-reactive/helper/adapter-operations.unit.test.java.mustache
src/main/resources/driven-adapter/dynamo-db/build.gradle.kts.mustache
src/main/resources/driven-adapter/dynamo-db/build.gradle.mustache
src/main/resources/driven-adapter/dynamo-db/config/dynamodb-config.java.mustache
src/main/resources/driven-adapter/dynamo-db/config/dynamodb-config.kt.mustache
src/main/resources/driven-adapter/dynamo-db/dynamo-db-template-adapter.java.mustache
src/main/resources/driven-adapter/dynamo-db/dynamo-db-template-adapter.kt.mustache
src/main/resources/driven-adapter/dynamo-db/helper/adapter-operations.java.mustache
src/main/resources/driven-adapter/dynamo-db/helper/adapter-operations.kt.mustache
src/main/resources/driven-adapter/dynamo-db/modelEntity.java.mustache

Update Dynamo DB configuration for AWS SDK 2.x

Update Dynamo DB configuration for AWS SDK 2.x

---

build.gradle
gradle.properties
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M01D19SonarSkipCompile.java
src/main/resources/structure/root/gradle.properties.mustache
src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M01D19SonarSkipCompileTest.java
src/test/resources/sonar-skip-compile/sonar-task-after.txt
src/test/resources/sonar-skip-compile/sonar-task-before.txt

Add systemProp.sonar.gradle.skipCompile=true to gradle properties
- x ] If the pull request has changed structural files, you have implemented an UpgradeAction according to the [guide](https://github.com/bancolombia/scaffold-clean-architecture/wiki/Contributing#upgradeaction)

fix(sonar): exclude dependency and skip compile from sonar task

---

README.md
examples-ca/example-redis/infrastructure/driven-adapters/redis/build.gradle
src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterJPA.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterMongoDB.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRedis.java
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterSecrets.java
src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
src/main/resources/driven-adapter/jpa-repository/build.gradle.kts.mustache
src/main/resources/driven-adapter/jpa-repository/build.gradle.mustache
src/main/resources/driven-adapter/mongo-reactive/build.gradle.kts.mustache
src/main/resources/driven-adapter/mongo-reactive/build.gradle.mustache
src/main/resources/driven-adapter/mongo-repository/build.gradle.kts.mustache
src/main/resources/driven-adapter/mongo-repository/build.gradle.mustache
src/main/resources/driven-adapter/redis-reactive/redis-template/build.gradle.kts.mustache
src/main/resources/driven-adapter/redis-reactive/redis-template/build.gradle.mustache
src/main/resources/driven-adapter/redis/redis-repository/build.gradle.kts.mustache
src/main/resources/driven-adapter/redis/redis-repository/build.gradle.mustache
src/main/resources/driven-adapter/redis/redis-template/build.gradle.kts.mustache
src/main/resources/driven-adapter/redis/redis-template/build.gradle.mustache
src/main/resources/driven-adapter/secrets-vault-reactive/definition.json
src/main/resources/driven-adapter/secrets-vault-reactive/secrets-config.java.mustache
src/main/resources/driven-adapter/secrets-vault-reactive/secrets-config.kt.mustache
src/main/resources/driven-adapter/secrets-vault/definition.json
src/main/resources/driven-adapter/secrets-vault/secrets-config.java.mustache
src/main/resources/driven-adapter/secrets-vault/secrets-config.kt.mustache
src/main/resources/structure/root/build.gradle.kts.mustache
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java

Added support for Vault secrets backend.  This PR resolves #428

feat(vault): Add vault secrets support

---

README.md
sh_generate_project.sh
src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterCognitoTokenProvider.java
src/main/resources/driven-adapter/cognito-token-provider/reactive/build.gradle.mustache
src/main/resources/driven-adapter/cognito-token-provider/reactive/cognito-credentials.java.mustache
src/main/resources/driven-adapter/cognito-token-provider/reactive/cognito-token-provider-config.java.mustache
src/main/resources/driven-adapter/cognito-token-provider/reactive/cognito-token-provider.java.mustache
src/main/resources/driven-adapter/cognito-token-provider/reactive/cognito-token-provider.test.java.mustache
src/main/resources/driven-adapter/cognito-token-provider/reactive/cognito-token-response.java.mustache
src/main/resources/driven-adapter/cognito-token-provider/reactive/definition.json
src/main/resources/driven-adapter/cognito-token-provider/reactive/token-provider.java.mustache
src/main/resources/driven-adapter/consumer-rest/reactive-rest-consumer/build.gradle.mustache
src/main/resources/driven-adapter/consumer-rest/rest-consumer/build.gradle.kts.mustache
src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskReactiveTest.java

Add cognito token provider from credentials and define a default cache to reuse a token

feat(cognito): Add cognito token provider with cache

---

.github/workflows/gradle.yml
src/main/java/co/com/bancolombia/Constants.java
src/main/resources/driven-adapter/mq-sender-sync/sample-mq-message-sender.java.mustache
src/main/resources/driven-adapter/mq-sender/req-reply-gateway.java.mustache
src/main/resources/driven-adapter/mq-sender/sample-mq-message-sender.java.mustache
src/main/resources/driven-adapter/mq-sender/sample-mq-req-reply.java.mustache
src/main/resources/entry-point/mq-listener-sync/sample-mq-message-listener.java.mustache
src/main/resources/entry-point/mq-listener/sample-mq-message-listener.java.mustache
src/main/resources/structure/root/build.gradle.mustache

Update commons jms to 2.0.1 which includes @ReqReply for fixed queues and removes some implementations, and allows multi broker connections.

fix(commonjms): Update commons jms to 2.0.1 version and generated code

---

README.md
src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
src/main/resources/structure/root/build.gradle.kts.mustache
src/main/resources/structure/root/build.gradle.mustache
src/main/resources/structure/root/main.gradle.mustache
src/test/java/co/com/bancolombia/task/GenerateStructureTaskTest.java

the option to configure the cover tool is eliminated, it remains preset jacoco

feat: remove cobertura plugin

---

.github/workflows/codeql.yml
.github/workflows/gradle.yml
.github/workflows/release.yml
.github/workflows/scorecards-analysis.yml
.github/workflows/secret-scanner.yml

Update release actions and conditions for automatic releases

fix(ci): Skip ci when automatic release push

---

.github/workflows/gradle.yml
sh_generate_project.sh
src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointGraphql.java
src/main/resources/entry-point/graphql-api/api-mutations.java.mustache
src/main/resources/entry-point/graphql-api/api-mutations.test.java.mustache
src/main/resources/entry-point/graphql-api/api-queries.java.mustache
src/main/resources/entry-point/graphql-api/api-queries.test.java.mustache
src/main/resources/entry-point/graphql-api/build.gradle.mustache
src/main/resources/entry-point/graphql-api/definition.json

Graphql update to use spring boot version and support reactive and imperative projects

fix(graphql): Graphql update

---

README.md
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
src/main/java/co/com/bancolombia/factory/validations/architecture/ArchitectureValidation.java
src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
src/main/resources/structure/root/build.gradle.mustache
src/main/resources/structure/root/main.gradle.mustache

- **fix**: apply fix to prevent concurrentModificationException while validating the clean architecture
- **feat**: included configuration to add pitest plugin and base configuration for mutation testing.

feat: add pitest support

---

.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/gradle.yml
.github/workflows/release.yml
.github/workflows/scorecards-analysis.yml
.github/workflows/secret-scanner.yml
.github/workflows/updater.yml
.pre-commit-config.yaml

Update Github actions configuration files for Scorecards and secret scanner using StepSecurity tool

fix(scanner): Update scorecard and secret scanner actions

---

.github/pull_request_template.md
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M10D02SonarRules.java
src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2023M10D02SonarRulesTest.java
src/test/resources/sonar-rules/after-merged.txt
src/test/resources/sonar-rules/before-merged.txt

Fix UpgradeAction for jacoco merged report adding arch unit issues to sonar
closes #436
closes #512

fix(archunitsonar): Fix UpgradeAction for jacoco merged report adding arch unit issues to sonar

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M11D16Gradle.java
src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M11D16GradleTest.java
src/test/resources/gradle-8.11-sample/main-after.txt
src/test/resources/gradle-8.11-sample/main-before.txt

Updated to Gradle version 8.11 according to the changes [Deprecated java plugin conventions](https://docs.gradle.org/current/userguide/upgrading_version_8.html#java_convention_deprecation)

feat(gradle): add UpgradeAction for gradle 8.11

---

src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M11D16Gradle.java
src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M11D16GradleTest.java

Add validation in Gradle 8.11 upgrade action to avoid duplicating `java {}` block in main.gradle file #585

fix(gradle): fix UpgradeAction for gradle 8.11

---

src/main/resources/entry-point/rest-webflux/router-functions/config.unit.test.java.mustache
src/main/resources/entry-point/rest-webflux/router-functions/definition.json

Create template for webflux router tests

fix: add config test when router option is true

---

src/main/java/co/com/bancolombia/factory/tests/performance/PerformanceTestJmeter.java
src/main/java/co/com/bancolombia/task/GeneratePerformanceTestTask.java
src/main/resources/test/performance-test/jmeter/Jmeter/Api/definition.json
src/test/java/co/com/bancolombia/task/GeneratePerformanceTestTaskTest.java

Generate only api performance-test when reactive-web or api-rest modules are created in the deployment folder path project

fix: Add api performance-test when reactive-web or api-rest modules exists

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/co/com/bancolombia/Constants.java
src/main/java/co/com/bancolombia/factory/pipelines/PipelineAzure.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2022M05D05.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2024M11D16Gradle.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2025M03D08Gradle.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2025M05D10Cache.java
src/main/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2025M08D01Sonar.java
src/main/resources/driven-adapter/mq-sender/sample-mq-message-sender.java.mustache
src/main/resources/driven-adapter/mq-sender/sample-mq-req-reply.java.mustache
src/main/resources/pipeline/azure/azure.yaml.mustache
src/main/resources/structure/root/build.gradle.mustache
src/main/resources/structure/root/main.gradle.mustache
src/main/resources/test/acceptance-test/build.gradle.mustache
src/test/java/co/com/bancolombia/factory/upgrades/actions/UpgradeY2025M08D01SonarTest.java
src/test/resources/sonar-properties/sonarqube-task-after.txt
src/test/resources/sonar-properties/sonarqube-task-before.txt

A new update action has been created to modify the `build.gradle` file.
*   The deprecated property `sonar.test` is updated to `sonar.tests`.
*   The `sonar.java.binaries` property is correctly configured with the value `**/build/classes/java/main`.
*   The `sonar.junit.reportsPath` property is correctly configured with the value `**/build/test-results/test`.
The Azure pipeline template and plugin dependencies are also updated.

feat: add update action for SonarQube properties
